---
title       : CoreML algorytms
subtitle    : From the beginings to the not
author      : metya
job         : Летняя Школа 2018, Deep Learning Workshop
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax]            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
guthub      :
  user: 'metya'
  repo: 'CoreML'
---

# A few base algorythms and even farther

---

# Regression
- Linear regression ([объяснение на хабре](https://habr.com/company/ods/blog/323890/))
- NonLinear Regression
- Descision Trees 
- Autoregression (ARIMA, etc.) 
  
(множественные модели, многомерные модели, регрессионные остатки)

---

# Classification
- Logistic regression ([объяснение на хабре](https://habr.com/company/ods/blog/323890/))
- Descision Trees ([объяснение на хабре](https://habr.com/company/ods/blog/322534/))
- K Nearest Neighbours ([объяснение на хабре](https://habr.com/company/ods/blog/322534/))
- Naive Bayes ([Wiki](https://ru.wikipedia.org/wiki/Наивный_байесовский_классификатор), [habr (свежак!)](https://habr.com/post/415963/))
- Linear discriminant analysis (Fisher's)
- Support Vector Machine ([хабр](https://habr.com/post/105220/))
- Genetics Algorithms
- Expectation-Maximization (EM) ([где то в интернете](https://basegroup.ru/community/articles/em))

---
# Clusterization
([Николенко, слайды](https://logic.pdmi.ras.ru/~sergey/teaching/mlau12/10-clustem.pdf), [воронцов, лекция](http://www.ccas.ru/voron/download/Clustering.pdf))
- K-means ([объяснение на хабре](https://habr.com/company/ods/blog/325654/))
- DBSCAN ([хабр](https://habrahabr.ru/post/322034/))
- Affinity Propagation ([habr](https://habr.com/post/321216/))
- EM 
- Self-Organaized Maps aka Kohonen's networks ([все там же отличная статья!](https://habr.com/post/338868/))
- Principal Component Analysis aka Понижение размерности ([объяснение на хабре](https://habr.com/company/ods/blog/325654/))
- t-SNE 

---
# Many of them together 
- Bagging aka Bootstrap aggregation (Random Forest, etc.) 
([объяснение на хабре](https://habr.com/company/ods/blog/324402/))

- Boosting ([все там же](https://habr.com/company/ods/blog/327250/), [дьяконов](https://alexanderdyakonov.wordpress.com/2017/06/09/градиентный-бустинг/comment-page-1/), [чья то неплохая курсовая](http://www.machinelearning.ru/wiki/images/9/9a/fonarev.overview_of_boosting_methods.pdf))

--- .middle

# FIN!
